### ISSUE TITLE
Request to non Cloud Run URL fail with EAI_AGAIN 

### ISSUE THREAD

**Issue by Mistic92** [ahmetb/runsd#19]
Hi, I'm trying to call non Cloud Run url. I was trying both with http and https but every time I'm getting
```"
getaddrinfo EAI_AGAIN platform.dev.xxxxxxx.com"
```

Is it possible to do requests to external url? In this case it's hosted on GKE but with external domain connected.

**Comment by ahmetb** [comment]
Yes it is, EAI_AGAIN is a timeout error I see.
Is there a chance runsd might've crashed? 

Can you enable logs (https://github.com/ahmetb/runsd#troubleshooting) and re-deploy then capture what's happening behind the scenes?

**Comment by Mistic92** [comment]
After few requests there is only this one log
```
I0205 13:06:58.949533 1 main.go:248] subprocess terminated
```
I'll test this again tomorrow or on Monday as I need to trigger full pipeline for this one service to test connection

**Comment by ahmetb** [comment]
That log line indicates your main app has crashed.

**Comment by Mistic92** [comment]
This issue was connected to #18
