### ISSUE TITLE
Would it be possible to use the host metadata server instead of the nameserver?

### ISSUE THREAD

**Issue by leandro-manifesto** [ahmetb/runsd#20]
I've been looking for this for a while and the recent change on the Cloud Run host nameserver is a bummer.

I know that the metadata server has the project id and number, not sure about the hash though.
Would the instance's hostname suffice?

**Comment by ahmetb** [comment]
> I've been looking for this for a while and the recent change on the Cloud Run host nameserver is a bummer.

If you're referring to the bug notes in the readme, I might be workaround that. Just could not find the time to hack on it yet.

> I know that the metadata server has the project id and number, not sure about the hash though.
Would the instance's hostname suffice?

Not sure what you're asking. The project hash is not in the metadata service, but it's in the Host header coming to your service. If you want to parse that, you can guess URLs within the project. However, you'll have to get+add a token to the outgoing request as usual (which runsd does for you). Hth

**Comment by leandro-manifesto** [comment]
> If you're referring to the bug notes in the readme, I might be workaround that. Just could not find the time to hack on it yet.

Yup, that's the one.

> Not sure what you're asking. The project hash is not in the metadata service, but it's in the Host header coming to your service. If you want to parse that, you can guess URLs within the project. However, you'll have to get+add a token to the outgoing request as usual (which runsd does for you). Hth

My idea was that, if it were possible to get the hash from the metadata server somehow, `runsd` could use it instead of the host nameserver to get it.

Also yes, having the app parse the Host, build the other service url and add the token would defeat the purpose of using `runsd` in the first place.

**Comment by ahmetb** [comment]
The bug we're suffering from is not that we query metadata service; it's rather that there's a bug in host nameserver and it returns `SERVFAIL` to requests like `foo.bar.metadata.internal.`; but it should be returning `NXDOMAIN`.
