### ISSUE TITLE
How to get Project Hash if service is not yet deployed?

### ISSUE THREAD

**Issue by madbbb** [ahmetb/runsd#24]
Sorry for asking question here.

I have `cloudbuild.yaml` file which builds an image and deploys it on Cloud Run, how do you figure out `CLOUD_RUN_PROJECT_HASH` if service is not yet deployed?

**Comment by ahmetb** [comment]
Sadly you can't. The only way to do this is to make runsd also capture ingress traffic, and look at the host header but I decided not to implement this as it won't work well for apps that hardcore port 8080.

**Comment by basickarl** [comment]
I am in the exact same boat as @madbbb :(

**Comment by ahmetb** [comment]
Nothing we can do in this repo. 

If you wanna automate deployment of runsd, you can deploy an unused placeholder service to that project and parse the project's hash for now. 

We might add deterministic URLs to Cloud Run at some point later.

**Comment by mohamnag** [comment]
I was wondering if this could not be retrieved from metadata endpoint? not really familiar with details of the cloud run however

**Comment by ahmetb** [comment]
Deploy an example service (Cloud Run offers an example image for you in the Cloud Console) and copy the hash from there, and delete the service.

**Comment by psteinroe** [comment]
For anyone like me that doesn't know the project hash is project-wide: It is project wide! So just deploy any service once, copy the hash and delete the service again. You can use the same hash for all services. 👍

**Comment by PavloSombra** [comment]
@ahmetb this fresh comment of @steinroe about hash was really helpful, and it occurred to me: why not generate this hash when somebody enables Cloud Run Admin API for the GCP project?

**Comment by RevoltEnergy** [comment]
@ahmetb this fresh comment of @steinroe about hash was really helpful, and it occurred to me: why not generate this hash when somebody enables Cloud Run Admin API for the GCP project?

**Comment by ahmetb** [comment]
> why not generate this hash when somebody enables Cloud Run Admin API for the GCP project?

FWIW I locked this conversation because this repository is not the place to make Cloud Run feature requests.
