### ISSUE TITLE
failed to fetch metadata token: metadata server responeded with code=500

### ISSUE THREAD

**Issue by eturan** [ahmetb/runsd#27]
Hi,

I have deployed two services in the same project to europe-west4 region. One of them is the 'curl' service coming from this repository and it has public access.

Second service is a very basic nodejs application that just returns static HTML. Service name is 'internaldocs'. If I make it publicly accessible, I'm able to get 200 response. 

However, when I make the 'internaldocs' service allow internal traffic and traffic from Cloud Load Balancing only and trying to access it from 'curl' service by proving the 'http://internaldocs' url I get the following error;

```
$ curl -sSLNv --http2 http://internaldocs

*   Trying ::1:80...
* Connected to internaldocs (::1) port 80 (#0)
 GET / HTTP/1.1
 Host: internaldocs
 User-Agent: curl/7.76.1
 Accept: */*
 Connection: Upgrade, HTTP2-Settings
 Upgrade: h2c
 HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
 
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2c
* Received 101
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 500 
< date: Sun, 25 Apr 2021 18:22:07 GMT
< 
{ [98 bytes data]
failed to fetch metadata token: metadata server responeded with code=500 500 Internal Server Error* Connection #0 to host internaldocs left intact
```
I believe I gave the right permissions to the services by following this document https://cloud.google.com/run/docs/authenticating/service-to-service#gcloud but obviously I'm missing something.

You think it might be a bug or misconfiguration? 

Have a nice one!

**Comment by ahmetb** [comment]
What's your QPS? Is it like <1 or >30? I wonder if the metadata service is throttling you somehow.

**Comment by eturan** [comment]
It's less than 1

**Comment by ahmetb** [comment]
1. I assume you use VPC connector with this target service, correct?

2. Does it repro if you don't use a VPC connector but just make service _internal_ by not giving allUsers access on IAM?

3. What happens when you put both services in the same VPC (assuming answer to 1 is yes)? Maybe "internal only and Load Balancer" requires both services to be in the same VPC.

Nothing else particularly come to mind. Maybe we can increase logging level in your deployment (see Troubleshooting) to get some verbosity.

**Comment by eturan** [comment]
Actually, there is no VPC in this project at all. It was not clear to me from documentation if we need to setup a VPC connector to achieve internal service-to-service communication. Is it mandatory?

Apart from that I will try the 2nd option you suggested and update here.

Thanks for the help, appreciated a lot 🙏

**Comment by eturan** [comment]
Okay problem has been solved and I learned two things;

1. Service Accounts can be disabled. We are using default compute SA of the project and it was somehow disabled. When I enabled it I was able to access 'internaldocs' from the 'curl' service
2. There was no VPC in the project. So if you want to allow internal traffic and traffic from Cloud Load Balancing you need to have VPC and VPC Connector attached to the Cloud Run services. I believe Google Cloud Run documentation especially [service-to-service communication document](https://cloud.google.com/run/docs/authenticating/service-to-service#gcloud) can be improved by mentioning this use case.

Thanks again for the help.

**Comment by ahmetb** [comment]
If you want to make a service internal, you don't need VPC Connector. Just IAM.

VPC connector is for other resources that are in vpc and load balancers.
