### ISSUE TITLE
Feeback on rc13 run as user

### ISSUE THREAD

**Issue by erzz** [ahmetb/runsd#31]
Having tested here are some findings:

Here we are trying to run with custom user = "node"

- Running with no other modification other than adding the "-user=node" flag results in a permission denied on runsd itself
- Adding a `chown node:node /bin/runsd` lets it run but then runsd quits as it has no permission to modify resolv.conf `F0505 07:19:47.187954 1 main.go:204] open /etc/resolv.conf: permission denied`

For reference, stage 2 of our dockerfile looks like:

```
# Stage 2
FROM node:14-alpine3.12

# Add https://github.com/ahmetb/runsd for auth and service discovery in cloud run services
ADD https://github.com/ahmetb/runsd/releases/download/v0.0.0-rc.13/runsd /bin/runsd
RUN chmod +x /bin/runsd && chown node:node /bin/runsd

RUN apk update --no-cache && apk upgrade --no-cache
RUN apk add "musl>=1.1.24-r10" "musl-utils>=1.1.24-r10"

ENV HOST 0.0.0.0
WORKDIR /home/node

COPY --chown=node:node --from=builder /home/node .

USER node

CMD ["runsd", "-user=node", "--", "yarn", "start"]
```

**Comment by ahmetb** [comment]
You can't use USER directive. I thought I explained why in #16.

**Comment by ahmetb** [comment]
Specifically this part: https://github.com/ahmetb/runsd/issues/16#issuecomment-832237743

Once we set `USER foo`, runsd will also be executed with that. That might limit us from (1) editing resolv.conf (2) listening on low ports like 53 and 80.

So I am afraid runsd needs to continue listening on these ports. Is that not acceptable?

**Comment by erzz** [comment]
Hi @ahmetb 

Just a note to say I have been swamped with other work so haven't had a great deal of time to play with it recently - hope to give some feedback next week

**Comment by ahmetb** [comment]
Assuming it's fixed.
