### ISSUE TITLE
Problem with Listenin gRPC Requests Over HTTP on Cloud Run

### ISSUE THREAD

**Issue by turgayozgur** [ahmetb/runsd#32]
I am not quite sure that the case handled by the runsd before. But now, there is an issue with or without runsd.

I was running my gRPC services on Cloud Run without any problem. But today, I realized they are no longer working over HTTP including the services that have no change for a long time.

The exception is The request :scheme header 'https' does not match the transport scheme 'http'."

The services receiving requests over HTTP and using the binary https://github.com/ahmetb/runsd as a parent process.

So, is there any change on Cloud Run side or is there anything that I am missing?

If I change the code to receive requests over HTTPS, probably they will work(not tested yet). But, it is not the point. They were running without any issue before.

I implemented the Program.cs and the docker file as explained on there https://cloud.google.com/run/docs/quickstarts/build-and-deploy/c-sharp and this is not working too.

![image](https://user-images.githubusercontent.com/2786640/117339432-65c3c680-aea8-11eb-9082-d9d5116f0374.png)

**Comment by ahmetb** [comment]
1. Does it repro without runsd (just to make sure it's a runsd issue).
2. Can you install an older version to see if it works?

I have never used gRPC with .NET so I don't know if I can help much here based on the exception message.

I test runsd with gRPC on Go and AFIAK that works.

Is the problem with how your server listens OR how your app makes requests? Because we don't really touch listening part at all (and your requests should be listening over http unencrypted, or its h2 equivalent which is h2c).

**Comment by turgayozgur** [comment]
1. Yes, with or without runsd, the results are same.
2. I was using rc.9 version. No longer working for this case. Same with rc.13.

I think the request is proxying over HTTPS to the service running on cloud run. Then the .NET service rejected due to the protocol error.

I have go services with the same setup and they are working as expected as you said. I think they work with or without HTTPS.

I am trying to create a  simple hello-world .NET docker container that works with gRPC to reproduce the issue.

**Comment by ahmetb** [comment]
Apologies I redirected you from stackoverflow.
If the problem happens without runsd, let's take that out of the picture and not mention it.



> I think the request is proxying over HTTPS to the service running on cloud run. Then the .NET service rejected due to the protocol error. Becase the service expecting over HTTP.

That's not exactly how it works.

Cloud Run services accept traffic only over https. (http is redirected)

But that does not mean your containerized application should handle https. It **has to** continue serving unencrypted traffic. The encryption is added later by the infrastructure.
 


> I am trying to create a simple hello-world .NET docker container that works with gRPC to reproduce the issue.

A minimal repro would help.

**Comment by ahmetb** [comment]
I left an answer on stackoverflow because it turns out I've tried this before:
https://stackoverflow.com/a/67424406/54929
