### ISSUE TITLE
How to dns resolve to cloudRun services across different GCP projects

### ISSUE THREAD

**Issue by KarstenBlohm** [ahmetb/runsd#37]
Hey there,
is there any way to resolve the internal cloud run service of another GCP project? In GKE I did this with internal load balancers and VPC peering. For CloudRun this seems to be different

**Comment by ahmetb** [comment]
You'd still need ILBs etc but I believe Cloud Run is not yet supported behind ILBs. 

This project is also not designed for cross-project discovery.
