### ISSUE TITLE
Shared VPC

### ISSUE THREAD

**Issue by okiirawan** [ahmetb/runsd#38]
Is runsd support Shared VPC using VPC Connector?

**Comment by ahmetb** [comment]
I am thinking yes but I have not tried. Nothing comes to mind why it wouldn't (see [this section](https://github.com/ahmetb/runsd/tree/dcd3d39ca2b75b84ffab3b4b647827c11b15a029#architecture) explaining how the tool works). Please try and report. 😇

**Comment by okiirawan** [comment]
I've tried by deploying 2 example application (curl-app) but when try it gives me error:
```
2021-07-15 10:04:01.333 WITI0715 03:04:01.333602 1 proxy.go:59] [director] receive req host=curl-app
Default
2021-07-15 10:04:01.333 WITI0715 03:04:01.333639 1 proxy.go:84] [director] rewrote host=curl-app to=curl-app-xxxxx-et.a.run.app new_url="https://curl-app-xxxxx-et.a.run.app/"
Default
2021-07-15 10:04:01.333 WITI0715 03:04:01.333685 1 proxytransport.go:77] [proxy] start: GET url=https://curl-app-xxxxxx-et.a.run.app/
Default
2021-07-15 10:04:01.367 WITI0715 03:04:01.367271 1 proxytransport.go:82] [proxy] end: GET url=https://curl-app-xxxxx-et.a.run.app/ took=33ms``
Default
2021-07-15 10:04:01.367 WIT2021/07/15 03:04:01 http: proxy error: context canceled
Default
2021-07-15 10:04:01.367 WIT2021/07/15 03:04:01 http: response.WriteHeader on hijacked connection from net/http/httputil.(*ReverseProxy).defaultErrorHandler (reverseproxy.go:188)
Warning
2021-07-15 10:04:04.851 WITTruncated response body. Usually implies that the request timed out or the application exited before the response was finished.
```
The configuration I use:
curl-app (target):
- Egress: All traffic through VPC connector
- Ingress: Internal traffic and authenticated

curl-app-2 (I call from this):
- Egress: All traffic through VPC connector
- Ingress: All traffic

**Comment by ahmetb** [comment]
Those logs seem benign (they just indicate the client probably canceled the request before it completed).

I just deployed with these settings and it worked fine for me. **That said my VPC is a regular VPC and not a shared VPC.**

target (gcr.io/cloudrun/hello image)

- -vpc-egress=all
- -ingress=internal
- allow test-acct-1@ahmetb-demo.iam.gserviceaccount.com to invoke (requires authentication)

caller (curl)

- no authentication (public)
- -ingress=all (default)
- -vpc-egress=all

if you can confirm on a non-shared VPC, that would immensely help. also please explain what response you see (output of curl).

**Comment by okiirawan** [comment]
Using same deployment like your (Not using shared VPC), still having same problem.
Here are the curl result:
```
$ curl -sSLNv --http2 http://hello

*   Trying ::1:80...
* Connected to hello (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: hello
> User-Agent: curl/7.77.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2c
* Received 101
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
```
Have done something wrong in the configuration?

**Comment by ahmetb** [comment]
Were you able to make it work without VPC connector at all? Or without runsd?

**Comment by okiirawan** [comment]
I'm able to authenticate without runsd..

And I'm also able authenticate in shared VPC without runsd, we need use VPC Service Control in the same perimeter .

**Comment by ahmetb** [comment]
So the issue indeed seems to be a shared VPC + runsd issue then?
I personally don't know which dynamics in shared VPC mode would cause this. Please refer to the Architecture section (https://github.com/ahmetb/runsd#architecture) to see how this tool does its job. I can't pinpoint a specific reason as to why it would not be compatible with shared VPC.

The only suspicion I have is that runsd modifies/replaces /etc/resolv.conf file heavily, and maybe in shared VPC mode there's something that's different than non-shared VPC mode.

Can you query the `/resolv.conf` endpoint of the example curl app?

**Comment by ahmetb** [comment]
closing this for now.
