### ISSUE TITLE
Incremental Rollout

### ISSUE THREAD

**Issue by klee310** [ahmetb/runsd#39]
We're trying out this runtime-modification, on a select number of services first. Do we need to apply the change for all containers, or only the source-container which is calling other services using the old method?

**Comment by ahmetb** [comment]
You need to update only the caller (source service).

**Comment by ahmetb** [comment]
Also:

> For my tracking purposes, please fill out the form at https://forms.gle/kCgEEiRqrmHhM65g6 if you are using runsd. Your feedback will be important in shaping this feature.

**Comment by klee310** [comment]
awesome. thanks for the quick response
