### ISSUE TITLE
Ability to run on Compute Engine

### ISSUE THREAD

**Issue by sorenhansendk** [ahmetb/runsd#41]
Will it be possible to run `runsd` as a process on a Compute Engine VM in Google Cloud?

I have tried to start the binary up on a VM with the following parameters, and it looks like it starting - but I can't connect to any services. I get an `502: Bad Gateway` error, when I try to connect to the services.

<pre>
./runsd -v=5 -gcp_region=europe-west4 -gcp_project_hash=[my-project-hash] -- wget http://[my-cloud-run-service]/hello
</pre>

**Comment by ahmetb** [comment]
> Will it be possible to run `runsd` as a process on a Compute Engine VM in Google Cloud?

runsd is not designed for this. It applies a series of hacks on the host environment that would easily ruin your VM's settings such as the DNS configuration.
