### ISSUE TITLE
Automatic authentication and how that works

### ISSUE THREAD

**Issue by vongohren** [ahmetb/runsd#43]
Hi! So I have two cloud runs going, both are in authed mode, and the one authed one uses the other service.
This tool talks about automatic authentication.

Does this work so that this tool adds the auth header nessecary to pass through the service?
Does this do that through a Bearer token or how?

Because right now, it does not work out of the box.
I have to add serviceaccount rights as an invoker on the service which is consumed by another service, to get this to work. Else i get 403 forbidden

Is there anything I need to configure to get authentication to work properly?

I am using v0.0.0-rc.15
And follow getting started.

**Comment by ahmetb** [comment]
Automatic=it injects the necessary account token header. Doesn't mean it'll adjust your IAM permissions for you. 

Default svcaccount has this permission, otherwise you need to assign manually
