### ISSUE TITLE
Usage without entrypoint subprocess

### ISSUE THREAD

**Issue by dblackherod** [ahmetb/runsd#44]
This is more of a question than an issue.
So, it appears that...
`1 main.go:104] specify subprocess as positional args, e.g: '/runsd -- python3 server.py'`
...meaning, for images without an explicit entrypoint (i.e. using docker-entrypoint.sh) would always complain (and fail).

Also,
`1 main.go:284] ipv6 stack not available: listen tcp6 [::1]:0: bind: cannot assign requested address`
...meaning, runsd executable may not be usable on lightweight images (for instance, alpine images)

**Question:**
How to use **runsd** without explicitly setting an entrypoint subprocess command.
I believe this is particularly useful when using official images that use default docker entrypoint.

An example showing how to **runsd** on (for instance) **[nginx:stable-alpine](https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile)** will definitely clarify my question.

**[nginx:stable-alpine](https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile)** exposes port 80 in its Dockerfile, causing this...
` 1 main.go:90] your Cloud Run application is set to run on PORT=80, this conflicts with runsd`
...and this happens after explicitly setting entrypoint subprocess to default docker-entrypoint.sh in Dockerfile ENTRYPOINT.

**Comment by ahmetb** [comment]
Yeah if your entrypoint is a sophisticated script, it won't prevent the port overlap. You have to find a way to run nginx process on another port. Runsd is a solution that requires entrypoint change unfortunately. The repo README explains how the hack works in detail.

**Comment by dblackherod** [comment]
So, somehow the container now complains that...
`nginx: [emerg] invalid host in upstream "http://environ-docgen:9000" in /etc/nginx/conf.d/nginx.conf:34`
...its the fastcgi_pass directive telling where to send requests. Destination container is also `runsd`ified.

Please see images showing dev and prod environments.
Personally, I believe this should have a simple solution, since its complain is straightforward.

![Screenshot (4)](https://user-images.githubusercontent.com/437805/153929404-c1e25388-1a56-44b2-b99f-e389f3f33d10.png)
![Screenshot (5)](https://user-images.githubusercontent.com/437805/153929499-131bc29a-7742-4cfc-aa7b-0dd3406e8512.png)

Any ideas how to resolve/workaround this?

**Comment by dblackherod** [comment]
Hey Ahmetb,
...just wanted to add that the _Cloud Run Invoker_ role is assigned to the gcloud service account (and also the _Cloud Run Service Agent_ role) in use by the container, so, in theory, IAM policy constraints should not be the issue here at all.
