### ISSUE TITLE
Usage without entrypoint subprocess #44

### ISSUE THREAD

**Issue by dblackherod** [ahmetb/runsd#46]
Hey Ahmetb,
_Yeah if your entrypoint is a sophisticated script, it won't prevent the port overlap. You have to find a way to run nginx process on another port. Runsd is a solution that requires entrypoint change unfortunately. The repo README explains how the hack works in detail._

> The _docker-entrypoint.sh_ file is the same that ships with **nginx:stable-alpine**. All I did was change the exposed port 80 to the ports the nginx container will `fastcgi_pass` to.

So, somehow the container now complains that...
`nginx: [emerg] invalid host in upstream "http://environ-docgen:9000" in /etc/nginx/conf.d/nginx.conf:34`
...its the `fastcgi_pass `directive telling where to send requests. Destination container is also `runsd`ified.

Please see images showing dev and prod environments.
Personally, I believe this should have a simple solution, since its complain is straightforward.

![Screenshot (4)](https://user-images.githubusercontent.com/437805/153929404-c1e25388-1a56-44b2-b99f-e389f3f33d10.png)
![Screenshot (5)](https://user-images.githubusercontent.com/437805/153929499-131bc29a-7742-4cfc-aa7b-0dd3406e8512.png)

The _Cloud Run Invoker_ role is assigned to the gcloud service account (and also the _Cloud Run Service Agent_ role) in use by the container, so, in theory, IAM policy constraints should not be the issue here at all.

Interestingly, omitting the scheme (http://) from the `fastcgi_pass` directive resolves the issue on dev (local vscode) environment, but in production (gcloud run) environment there are no complains, and no service intercommunication either.

Please see the images below for more reference.

![Screenshot (6)](https://user-images.githubusercontent.com/437805/153949407-36e72cb6-22ed-4b5e-a8bb-95af3f635c6d.png)

![Screenshot (7)](https://user-images.githubusercontent.com/437805/153949465-66892e21-46b9-4f69-b924-295959a3fff6.png)

![Screenshot (8)](https://user-images.githubusercontent.com/437805/153949493-974e8570-6c68-4728-8d61-493a7ff0e8ed.png)

...and yes, the cloud run container port was changed to reflect the new (`runsd`ified) container port exposed (8080). The result of that attempt is this...

![Screenshot (9)](https://user-images.githubusercontent.com/437805/153949928-d4023fdd-55a1-45af-a2a0-bfefa90f1c81.png)

Dev (local vscode) environment continues to work as expected, shutting down `runsd`ified containers gracefully.

![Screenshot (10)](https://user-images.githubusercontent.com/437805/153952233-93e761cb-bd04-417f-94b8-0ec13db75ea6.png)

My next question, given the above reconnaissance is... why does the schemeless fastcgi_pass directive even work?, plus what is the proper way to do service discovery and communication with runsd on GCP?
I feel like `runsd `internal scheme [http->https] redirection is the culprit for the bad request although I might be wrong.

**Comment by ahmetb** [comment]
I don't know why you opened a new issue instead of continuing on #44. 

You have a pretty detailed request –and I unfortunately don't have the time to understand and help with your case. I don't work on Cloud Run anymore.

This tool already works for many people for most of the use cases and is in a stable state. Try to start from a very simple deployment (without involving nginx) and work your way from there. Unfortunately I just don't have time to understand these settings of nginx which I have never needed and used.

As I said, runsd works is explained in detail on my repo and the blog post linked on the repo homepage. Also keep in mind that you don't have to use runsd, it's a convenience tool.

**Comment by dblackherod** [comment]
Hi Ahmetb,
I reopened a fresh issue since you closed the issue, and I know it needed to be fresh issue to get your attention on it after closing it. Anyway, I am certain that `runsd `does not work with nginx containers. I have diagnosed thoroughly without success.

At some point I figured maybe, since the container port serves ssl and gcloud run service urls are https by default, then that 400 Bad Request error would go away if the upstream destination port was 80 and not the published one. Alas, this was not so.

Final attempt was to `fastcgi_pass` to <service-name>:80 (without schemes, since` invalid host in upstream` errors arise from that). This caused 502 Bad Gateway error on dev environment, and same 400 Bad request error on GCP Cloud Run.

The main reason I conclude that `runsd` does not work with official images that expose port 80 by design, is that the schemed url for the `fastcgi_pass` directive that indicates the destination (upstream) container just does not work with such images.

Personally, I would consider this a known bug. Overall, nice work, and more power to your elbow.

**Comment by dblackherod** [comment]
Hi Ahmetb,
I reopened a fresh issue since you closed the issue, and I know it needed
to be fresh issue to get your attention on it after closing it. Anyway, I
am certain that runsd does not work with nginx containers. I have diagnosed
thoroughly without success.

At some point I figured maybe, since the container port serves ssl and
gcloud run service urls are https by default, then that 400 Bad Request
error would go away if the upstream destination port was 80 and not the
published one. Alas, this was not so.

Final attempt was to fastcgi_pass to :80 (without schemes, since invalid
host in upstream errors arise from that). This caused 502 Bad Gateway error
on dev environment, and same 400 Bad request error on GCP Cloud Run.

The main reason I conclude that runsd does not work with official images
that expose port 80 by design, is that the schemed url for the
fastcgi_pass directive
that indicates the destination (upstream) container just does not work with
such images.

Personally, I would consider this a known bug. Overall, nice work, and more
power to your elbow.

**Comment by ahmetb** [comment]
Please stop spamming the repo. You need to learn open source etiquette. 

I am pretty sure it would work with nginx if you configure the ports correctly. So please try to understand how this tool works. There's an explanation in the readme. 

Stop opening further issues about this.
