### ISSUE TITLE
Project state

### ISSUE THREAD

**Issue by Igloczek** [ahmetb/runsd#49]
Hello there 👋 

I wonder about the state of this project, looks like you stopped development roughly 2 years ago, never got a stable release, but there is no information about it.

It's not needed anymore, because GCP built this in, or there is some successor?

I'd love to hear something about it.

**Comment by ahmetb** [comment]
No but it should be working. Does something need to have commits all the time?

**Comment by Igloczek** [comment]
Nah, but usually, it's a thing for a long living, stable projects, while those in versions "0.0.0-rc.15" or similar, have some good reason for not being developed anymore.
